export const logos = {
	"Atlanta Reign" : "atlanta_reign_logo.png",
	"Boston Uprising" : "boston_uprising_logo.png",
	"Chengdu Hunters" : "chengdu_hunters_logo.png",
	"Dallas Fuel" : "dallas_fuel_logo.png",
	"Florida Mayhem" : "florida_mayhem_logo.png",
	"Guangzhou Charge" : "guangzhou_charge_logo.png",
	"Hangzhou Spark" : "hangzhou_spark_logo.png",
	"Houston Outlaws" : "houston_outlaws_logo.png",
	"London Spitfire" : "london_spitfire_logo.png",
	"Los Angeles Gladiators" : "los_angeles_gladiators_logo.png",
	"Los Angeles Valiant" : "los_angeles_valiant_logo.png",
	"New York Excelsior" : "new_york_excelsior_logo.png",
	"Paris Eternal" : "paris_eternal_logo.png",
	"Philadelphia Fusion" : "philadelphia_fusion_logo.png",
	"San Francisco Shock" : "san_francisco_shock_logo.png",
	"Seoul Dynasty" : "seoul_dynasty_logo.png",
	"Shanghai Dragons" : "shanghai_dragons_logo.png",
	"Toronto Defiant" : "toronto_defiant_logo.png",
	"Vancouver Titans" : "vancouver_titans_logo.png",
	"Washington Justice" : "washington_justice_logo.png",
};